# Generated by Django 2.1.7 on 2019-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='document',
            field=models.FileField(upload_to='input/'),
        ),
    ]
