# Generated by Django 2.1.7 on 2019-02-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20190226_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='input/')),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
